# golangci-lint configuration
# https://golangci-lint.run/usage/configuration/

run:
  # Timeout for analysis
  timeout: 5m
  
  # Include test files
  tests: true
  
  # Directories to skip
  skip-dirs:
    - vendor
    - bin
    - dist
    - .git
  
  # Files to skip
  skip-files:
    - ".*\\.pb\\.go$"
    - ".*_generated\\.go$"

# Output configuration
output:
  # Format: colored-line-number|line-number|json|tab|checkstyle|code-climate
  format: colored-line-number
  
  # Print lines of code with issue
  print-issued-lines: true
  
  # Print linter name in the end of issue text
  print-linter-name: true

# Linters settings
linters-settings:
  errcheck:
    # Report about not checking of errors in type assertions
    check-type-assertions: true
    
    # Report about assignment of errors to blank identifier
    check-blank: true
  
  govet:
    # Enable all analyzers
    enable-all: true
  
  gofmt:
    # Simplify code
    simplify: true
  
  goimports:
    # Put imports beginning with prefix after 3rd-party packages
    local-prefixes: github.com/rizkylab/Go-SecureVibes
  
  golint:
    # Minimal confidence for issues
    min-confidence: 0.8
  
  goconst:
    # Minimal length of string constant
    min-len: 3
    # Minimum occurrences of constant string count to trigger issue
    min-occurrences: 3
  
  misspell:
    # Correct spellings using locale preferences
    locale: US
  
  lll:
    # Max line length
    line-length: 120
    # Tab width
    tab-width: 4
  
  unused:
    # Treat code as a program (not a library)
    check-exported: false
  
  unparam:
    # Inspect exported functions
    check-exported: false
  
  nakedret:
    # Max number of lines for a naked return
    max-func-lines: 30
  
  prealloc:
    # Report preallocation suggestions only on simple loops
    simple: true
    range-loops: true
    for-loops: false
  
  gocritic:
    # Enable multiple checks by tags
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    
    disabled-checks:
      - dupImport
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc
  
  funlen:
    lines: 100
    statements: 50
  
  cyclop:
    # Max cyclomatic complexity
    max-complexity: 15
  
  gocyclo:
    # Minimal cyclomatic complexity to report
    min-complexity: 15

linters:
  # Disable all linters
  disable-all: true
  
  # Enable specific linters
  enable:
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - dupl
    - errcheck
    - exportloopref
    - exhaustive
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - golint
    - gomnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - rowserrcheck
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace

issues:
  # Excluding configuration per-path, per-linter, per-text and per-source
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - funlen
    
    # Exclude known linters from partially hard-vendored code
    - path: internal/hmac/
      text: "weak cryptographic primitive"
      linters:
        - gosec
    
    # Exclude some staticcheck messages
    - linters:
        - staticcheck
      text: "SA9003:"
    
    # Exclude lll issues for long lines with go:generate
    - linters:
        - lll
      source: "^//go:generate "
  
  # Independently of option `exclude` we use default exclude patterns
  exclude-use-default: false
  
  # Maximum issues count per one linter
  max-issues-per-linter: 0
  
  # Maximum count of issues with the same text
  max-same-issues: 0
  
  # Show only new issues
  new: false
